ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Caps_Lock: noop
    Control_L: noop
    Control_R: noop
    Eisu_toggle: clear
    Shift_L: commit_code
    Shift_R: commit_code
config_version: 0.36.custom.691352737
customization: 691352737
key_binder:
  bindings:
    - {accept: comma, send: Page_Up, when: has_menu}
    - {accept: period, send: Page_Down, when: has_menu}
    - {accept: semicolon, send: 2, when: has_menu}
menu:
  page_size: 5
punctuator:
  half_shape:
    "!": "！"
    "\"": {pair: ["“", "”"]}
    "$": "￥"
    "'": {pair: ["‘", "’"]}
    ",": "，"
    .: "。"
    "/": "/"
    ":": "："
    ";": "；"
    "<": "《"
    ">": "》"
    "?": "？"
    "[": "【"
    "\\": "、"
    "]": "】"
    "^": "……"
    _: "——"
    "|": "·"
recognizer:
  patterns:
    email: "^[A-Za-z][-_.0-9A-Za-z]*@.*$"
    uppercase: "[A-Z][-_+.'0-9A-Za-z]*$"
    url: "^(www[.]|https?:|ftp[.:]|mailto:|file:).*$|^[a-z]+[.].+$"
schema_list:
  - schema: wubi86
  - schema: double_pinyin_flypy
switcher:
  caption: "〔方案选单〕"
  hotkeys:
    - "Control+grave"